### ISSUE TITLE
Any ability to add more perfdata?

### ISSUE THREAD

**Issue by mon0brew** [mhoogveld/check_cisco_ip_sla#6]
We have IPSLA checks setup for VoIP jitter and MOS score. Is it possible to add these metrics into the returned perfdata?

Sample output of one of our IPSLA configs:
IPSLAs Latest Operation Statistics

IPSLA operation id: 101292
Type of operation: udp-jitter
        Latest RTT: 42 milliseconds
Latest operation start time: 13:37:28 gmt Mon Mar 20 2017
Latest operation return code: OK
RTT Values:
        Number Of RTT: 1000             RTT Min/Avg/Max: 41/42/75 milliseconds
Latency one-way time:
        Number of Latency one-way Samples: 1000
        Source to Destination Latency one way Min/Avg/Max: 19/20/53 milliseconds
        Destination to Source Latency one way Min/Avg/Max: 21/22/27 milliseconds
Jitter Time:
        Number of SD Jitter Samples: 999
        Number of DS Jitter Samples: 999
        Source to Destination Jitter Min/Avg/Max: 0/1/15 milliseconds
        Destination to Source Jitter Min/Avg/Max: 0/1/5 milliseconds
Packet Loss Values:
        Loss Source to Destination: 0
        Source to Destination Loss Periods Number: 0
        Source to Destination Loss Period Length Min/Max: 0/0
        Source to Destination Inter Loss Period Length Min/Max: 0/0
        Loss Destination to Source: 0
        Destination to Source Loss Periods Number: 0
        Destination to Source Loss Period Length Min/Max: 0/0
        Destination to Source Inter Loss Period Length Min/Max: 0/0
        Out Of Sequence: 0      Tail Drop: 0
        Packet Late Arrival: 0  Packet Skipped: 0
Voice Score Values:
        Calculated Planning Impairment Factor (ICPIF): 11
        MOS score: 4.06
Number of successes: 9
Number of failures: 0

**Comment by mhoogveld** [comment]
The framework is there to support this. I'll have to see what would be the best way to integrate this, but it sounds interesting.

Would you be primarily interested in performance data or also in a returned status (ok/warn/crit) based on set thresholds. There are a lot of values to set thresholds for, maybe just ICPIF and MOS (and RTT and jitter... and loss... :) )
Also, there are a lot of values that average over quite a long period, so any warning would be a little late. 

With regards to the perf data, I expect you'd like as much as possible (why not?).
This would result in something like this:
`OK - IP SLA 101292 | LatestRTT=42ms  RTT=41ms;42;75 SD_Lat=19ms;20;53 DS_Lat=21ms;22;27 SD_Jitter=0;1;15 DS_Jitter=0ms;1;5 SD_Loss=0 SD_LossPeriods=0 SD_LossLength=0;0 SD_LossInterLossLength=0;0 DS_Loss=0 DS_LossPeriods=0 DS_LossLength=0;0 DS_LossInterLossLength=0;0 OutOfSeq=0 TailDrop=0 PcktLateArrival=0 PcktSkipped=0 ICPIF=11 MOS=4.06`

Other than with echo IPSLA's, I don't see any use for supporting more than one IPSLA per check.

Please let me know what you think about this.

**Comment by mon0brew** [comment]
My network guys state that perfdata collection is the most important. RTT, Jitter, Loss and MOS
If the ability to alert on MOS below a certain level were easily attainable, that would be great.

**Comment by mon0brew** [comment]
Any luck on this?

**Comment by mhoogveld** [comment]
I've been trying to find the time to work on this and I hope to look into this the coming weekend / week.
Just to be sure, are you using a jitter(9) or a voip(13) type SLA? (or even icmpJitter or ethernetJitter)
Use snmpwalk -v 1 -c [your-community] [your-ip] .1.3.6.1.4.1.9.9.42.1.2.1.1.4 to check

**Comment by mon0brew** [comment]
jitter(9) - greatly appreciated.

**Comment by mhoogveld** [comment]
Could you check if the latest version of the script in branch issue-6 works ok for you?
It works well for me except for the MOS score. I can't seem to get any MOS of ICPIF value out of a Cisco device. All I get is 0. Maybe the device just does not support these values.
Any feedback would be great.

[Direct link](https://raw.githubusercontent.com/mhoogveld/check_cisco_ip_sla/issue-6/check_cisco_ip_sla.py)

**Comment by mon0brew** [comment]
Getting this output when I try to run the new version:

`Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_cisco_ip_sla.py", line 854, in <module>
    result = checker.run()
  File "/usr/local/nagios/libexec/check_cisco_ip_sla.py", line 82, in run
    self.check()
  File "/usr/local/nagios/libexec/check_cisco_ip_sla.py", line 803, in check
    self.collect_perfdata_jitter(requested_entry)
  File "/usr/local/nagios/libexec/check_cisco_ip_sla.py", line 759, in collect_perfdata_jitter
    v=jitter_info["num_over_threshold"]
KeyError: 'num_over_threshold'
`

**Comment by mon0brew** [comment]
I can run a list or just a basic check without --perf and it returns OK. Just adding perfdata results the above output.

**Comment by mhoogveld** [comment]
Please check now. I added an exception for when that specific value is not returned by the device.

**Comment by mon0brew** [comment]
This looks great!

OK - 1 OK | RTT=21;22.6;32 'RTT variance'=510.3 'Avg jitter'=1 'Avg jitter SD'=1 'Avg jitter DS'=1 'Avg latency SD'=15 'Avg latency DS'=7 'MOS'=406 'ICPIF'=11 'Packet loss SD'=1 'Packet loss DS'=0 'Packet out of seq'=0 'Packet MIA'=0 'Packet late arrival'=0 'rtt'=22ms

The only thing I see that's an issue here is that MOS needs to have the decimal point set. 406 should be 4.06

**Comment by mhoogveld** [comment]
Thanks for the feedback!
How about now? I've also fixed the MOS and ICPIF thresholds

**Comment by mon0brew** [comment]
That did the trick. Plugin looks perfect. I'd recommend releasing this new version. If you update it on the Nagios exchange, I'll make sure that the Nagios team announces it on their Twitter feed. This should be a widely announced plugin as it provides a tremendous amount of value in Cisco monitoring. Your efforts are GREATLY appreciated.

**Comment by mhoogveld** [comment]
Thanks! I will do that, after some final touches (documentation etc)

**Comment by mhoogveld** [comment]
Fixed/added in release v1.1.0
Thanks for your help and testing mon0brew!

**Comment by mon0brew** [comment]
Thanks are all to you! My network engineers are giddy at this release.
