### ISSUE TITLE
Python3 dict sort problem

### ISSUE THREAD

**Issue by kovaxur** [mhoogveld/check_cisco_ip_sla#9]
Hi,
I got the following prolem, when running with --entries all: (python 3.6)

Using parameters:
 Hostname:        XXX
 SNMP-version:    3
 Community:       public
 Security-name:   XXX
 Security-level:  authPriv
 Password:        None
 Auth-protocol:   SHA
 Auth-password:   XXX
 Priv-protocol:   AES
 Priv-password:   XXX
 Mode:            check
 SLA entries:     all
 Perf-data:       True
 Critical-pct:    100
 Warning-pct:     50
 Critical:        None
 Warning:         None
 Critical MOS:    None
 Warning MOS:     None
 Critical ICPIF:  None
 Warning ICPIF:   None
 Verbosity:       2

Starting SNMP-walk for rttMonCtrlAdminTable (.1.3.6.1.4.1.9.9.42.1.2.1.1)
Starting SNMP-walk for rttMonCtrlOperTable (.1.3.6.1.4.1.9.9.42.1.2.9.1)
Starting SNMP-walk for rttMonLatestRttOperTable (.1.3.6.1.4.1.9.9.42.1.2.10.1)
Starting SNMP-walk for rttMonLatestJitterOperTable (.1.3.6.1.4.1.9.9.42.1.5.2.1)
<class 'dict_keys'>
Traceback (most recent call last):
  File "./check_cisco_ip_sla.py", line 931, in <module>
    result = checker.run()
  File "./check_cisco_ip_sla.py", line 84, in run
    self.check()
  File "./check_cisco_ip_sla.py", line 845, in check
    requested_entries.sort(key=int)

The problem is this:
https://stackoverflow.com/questions/28039155/dict-items-object-has-no-attribute-sortreplace-min

I solved it by changed the following line (line 841):
requested_entries = self.rtt_dict.keys()
to:
requested_entries = list(self.rtt_dict.keys())

It's working now with pyhon 3.6 as well :)

Thanks,
Daniel

**Comment by mhoogveld** [comment]
Thanks a lot for reporting this.
Should be fixed in version 1.1.1
